### ISSUE TITLE
new powerline network?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/g8#10]
http://www.amazon.co.uk/TP-LINK-TL-WPA4230P-Powerline-Extender-Multiple/dp/B00K0MJ30G/
<img width="973" alt="new-powerline-adapter" src="https://cloud.githubusercontent.com/assets/194400/11305721/dbbc3656-8fa5-11e5-99e3-c01d01bac2a0.png">

**Comment by ghost** [comment]
http://www.amazon.co.uk/gp/product/B00K0MJ30G £44.49 on Cyber Monday ...

**Comment by nelsonic** [comment]
Done. :+1:
