### ISSUE TITLE
Bike Mount

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/g8#14]
http://www.evanscycles.com/products/clug/roadie-storage-mount-ec103200
![clug](http://images.evanscycles.com/product_image/image/6e6/914/00f/165221/large/clug-roadie-storage-mount.jpg)

**Comment by iteles** [comment]
Nice pillow :expressionless:

**Comment by nelsonic** [comment]
Steadyrack
https://www.youtube.com/watch?v=rktKx5Zqchs
https://www.kickstarter.com/projects/1249866640/steadyrack-bike-rack-love-your-bike
sadly, it didn't reach its funding goal on Kickstarter...
