### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/g8#27]
Logitech Z-906 5.1 Surround Sound Speakers
![logitech-z-906-speakers](https://cloud.githubusercontent.com/assets/194400/11171848/7f1f6118-8bf2-11e5-94cf-bbcf3779abcc.jpg)
http://www.amazon.co.uk/Logitech-Z-906-Surround-Sound-Speakers/dp/B004MY4PU6/

LG BH7240B 1200w
<img width="989" alt="lg-bh7240b-speakers" src="https://cloud.githubusercontent.com/assets/194400/11171874/eadb2810-8bf2-11e5-8ae2-91cfd203c7d9.png">
http://www.amazon.co.uk/LG-BH7240B-Channel-Satellite-Speakers/dp/B00JECTDQC/

**Comment by iteles** [comment]
_Note: The ones from the office aren't really in use because of the lack of sound-proofing in the house._

**Comment by nelsonic** [comment]
I'm _aware_ of that fact. I actually _intend_ on using the speakers _currently_ in the office at home, however removing them from their current location will require a day when our guest is not home because they are "_installed_" ...

I was merely recording the fact that I'd done a bit of research into the best alternatives.

**Comment by iteles** [comment]
👌🏻💋

**Comment by nelsonic** [comment]
Soooooooooooooooo Tempted....!!!
<img width="879" alt="speakers-deal" src="https://cloud.githubusercontent.com/assets/194400/11440855/fd7a241c-94fd-11e5-8609-a6522abbf3ad.png">

**Comment by nelsonic** [comment]
Sadly, unless we can _totally_ sound-proof the door speakers are a waste of time.
