### ISSUE TITLE
Reading Chair

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/g8#30]
Chair or Beanbag?

**Comment by ghost** [comment]
https://www.gumtree.com/p/chairs-and-stools/couple-of-designer-lounge-chair-wilkhahn-/1143244919
![chair-side](https://cloud.githubusercontent.com/assets/8533973/11456552/3937fbfa-9684-11e5-854b-787bb81f12aa.JPG)

**Comment by ghost** [comment]
http://www.wilkhahn.com/en/products/conference-and-visitor-chairs-seating/stitz2/
![stitz2-standing-aid-chair](https://cloud.githubusercontent.com/assets/8533973/11456555/5af73d50-9684-11e5-9dcc-3783c794cd22.jpg)

**Comment by nelsonic** [comment]
done.

**Comment by iteles** [comment]
What did you go for? ;)
