### ISSUE TITLE
Earphones

### ISSUE THREAD

**Issue by ghost** [nelsonic/g8#32]
Encomendas-me estes? http://www.amazon.co.uk/gp/product/B00HSJRSQU

**Comment by ghost** [comment]
This USB Drive: http://www.amazon.co.uk/dp/B00YFI1EBC

**Comment by ghost** [comment]
Helmet Camera: http://www.amazon.co.uk/gp/product/B00WUA0M42
[cash back](http://www.amazon.co.uk/b/ref=amb_link_198087327_1?ie=UTF8&node=5517495031&pf_rd_m=A3P5ROKL5A1OLE&pf_rd_s=qpe-title-tag&pf_rd_r=1WD8VP661022NYWJKQG5&pf_rd_t=201&pf_rd_p=722574927&pf_rd_i=B00WUA0M42)

**Comment by edwardcodes** [comment]
+ Grade A: http://www.ebay.co.uk/itm/Refurb-ThinkPad-X1-Carbon-i7-3667U-2-00GHz-8GB-240GB-SSD-W8-Pro-64-Bit-GradeA-/371453760246 £599
+ Grade B: http://www.ebay.co.uk/itm/Refurb-ThinkPad-X1-Carbon-i7-3667U-2-00GHz-8GB-240GB-SSD-W8-Pro-Ultrabook-/321924334704 £399
+ X230 with SSD: http://www.ebay.co.uk/itm/Lenovo-ThinkPad-X230-intel-Core-i5-2-6GHz-12-5-WEBCAM-Laptop-8GB-RAM-240GB-SSD-/231631028716

**Comment by nelsonic** [comment]
Done.
