### ISSUE TITLE
Mount ergotron for monitor

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/g8#39]
Move ergotron to its new home.

**Comment by nelsonic** [comment]
Totes done.
![dsc_0823](https://cloud.githubusercontent.com/assets/194400/12072633/bb165e70-b0e0-11e5-8e63-9c032f44cc1f.JPG)

**Comment by nelsonic** [comment]
This is what I look like working in an un-heated room in London..
![dsc_0833](https://cloud.githubusercontent.com/assets/194400/12073896/2f28e6b4-b12e-11e5-8cc1-7c28557e89c0.JPG)

**Comment by iteles** [comment]
❤️
