### ISSUE TITLE
contact electrician

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/g8#4]
Contact Electrician ASAP to find out how much it will cost extend Power.

**Comment by nelsonic** [comment]
@iteles see: https://docs.google.com/document/d/1F7hzx2CBlQ6lQaeOl07yGKCSir3z5wKKSpc6LBFKAzI/edit?usp=sharing

**Comment by iteles** [comment]
:+1: I also followed up with Kate this morning for her recommended electrician and will let you know as soon as I hear back.

**Comment by nelsonic** [comment]
Jerome is a true professional & craftsman.
He contacted me shortly after I posted the job description on Rated People, and offered to visit our house the next day. After quoting a great price and timeline his team were able to start quickly and exceeded our expectations. We would definitely use his expert services again and recommend him to anyone else. Overall a great experience. Thanks again!

**Comment by nelsonic** [comment]
Done. spent it.
