### ISSUE TITLE
Install Powerline Adapters for Faster Internt

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/g8#40]
Self-explanatory.
relates to: https://github.com/nelsonic/g8/issues/10

**Comment by nelsonic** [comment]
![dsc_1016](https://cloud.githubusercontent.com/assets/194400/12361037/8d5c1b86-bbb3-11e5-92b1-ce9a902832bf.JPG)
![screenshot_2016-01-15-18-11-40](https://cloud.githubusercontent.com/assets/194400/12361041/98aae828-bbb3-11e5-9661-e1aac2e7afe1.png)

**Comment by iteles** [comment]
:+1: Nice!
