### ISSUE TITLE
Prep & Take "Book Wall" Header Photo

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/g8#53]
Need to get this done _Today_!

**Comment by nelsonic** [comment]
Raw Photo:
![dsc_1375](https://cloud.githubusercontent.com/assets/194400/12869863/3e86ced0-cd23-11e5-8b79-81626e334ccc.JPG)
Test Video: https://drive.google.com/file/d/0B5V2LgJnobyMMUo0UHNmam9nTnM

**Comment by nelsonic** [comment]
Cropped:
![book-wall-raw-cropped](https://cloud.githubusercontent.com/assets/194400/12869888/02bf0de4-cd24-11e5-96a6-6ab0b9f11ecf.JPG)

**Comment by nelsonic** [comment]
Twitter header:
![nelsonic-book-wall-twitter-header](https://cloud.githubusercontent.com/assets/194400/12869899/5d589a54-cd24-11e5-8c6d-6b89a2fb54ac.png)
Not quite what I was hoping for... but it will do. :+1:

**Comment by iteles** [comment]
A little crooked but still pretty cool!

**Comment by nelsonic** [comment]
I took about 30 pictures... could not get a single one to be "perfect"... :disappointed:
